### ISSUE TITLE
Nuffield Department for Population Health Scraper

### ISSUE THREAD

**Issue by njall** [njall/TeSS_scrapers#5]
ICAL and RSS feeds available
https://www.ndph.ox.ac.uk/events

**Comment by anenadic** [comment]
This provider has an RSS feed, an iCal, and also uses bits of RDFa. However, neither method gives all information
  about events we need. iCal does not contain link to the event nor location. RSS feed does not contain end date,
  and location. Structured data is also patchy, not implemented properly and also missing a few event properties. For
  this reason, we resorted to parsing good all HTML.

  Provider provides events as pages which are loaded on demand via AJAX as JSON, containing lists of HTML snippets
  about events that are then injected into the page directly. We are getting all these pages, extracting HTML
  snippets from JSON, putting them into a dummy HTML document and then parsing the document to extract the data we
  need.
